### ISSUE TITLE
icon-white unsorted style missing in theme.bootstrap.css

### ISSUE THREAD

**Issue by pmolaro** [christianbach/tablesorter#6]
I'm using tablesorter 2.17.1, with the bootstrap theme.  I recently updated my tables' headers to be dark blue and tried to pass in the icon-white style to make the sort control icons white.  The style is correctly applied, and if I sort ascending or descending the single arrow icon is white. However the default unsorted icon is still black.

I looked at the theme.bootstrap.css and saw the style is missing for the icon-white version.  I found the white unsorted image in the images directory and made a base64 string out of it and added a new style to resolve the issue.  

To fix the issue you can add this style to /css/theme.bootstrap.css file:

``` css
.tablesorter-bootstrapvvhs .icon-white .bootstrap-icon-unsorted {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAOCAYAAAD5YeaVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWVJREFUeNqUUL9Lw2AUTGP8mqGlpBQkNeCSRcckEBcHq1jImMElToKuDvpHFMGhU0BQcHBwLji6CE1B4uB/INQsDi4d2jQ/fPeZxo764OV6915f7lLJ81xot9tCURXqdVEUr7IsO6ffH9Q5BlEUCaLwWxWqTcbYnaIoh0Dw4gAvcWlxq1qt9hqNxg6hUGAP+uIPUrGs0qXLer2+v/pTX6QpxLtkc2U2m53ACb8sSdIDXerSEms2m6+DweAICA4d89KGbduf9MpEVdXQ9/2LVqv1CASHjjn3iq/x1xKFfxQPqGnada1W86bT6SiO42OS3qk3KPStLMvbk8nkfjwen/LLuq6blFymMB0KdUPSGhAcOualjX6/f0bCiC7NaWGPQr0BwaFjzn0gYJqmLAiCA8/zni3LmhuGkQPBoWPOPwQeaPIqD4fDruu6L6Zp5kBw6IudchmdJAkLw3DXcZwnIPjy/FuAAQCiqqWWCAFKcwAAAABJRU5ErkJggg==);
}
```

I haven't checked the other theme css files but they too should probably be checked for this bugs.

thx!
pmolaro
